version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "maintenance"
      - "dependencies"
      - "lazyssh"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "gh-actions"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "maintenance"
      - "dependencies"

  - package-ecosystem: "gomod"
    directory: "/examples"
    schedule:
      interval: "weekly"
    labels:
      - "maintenance"
      - "dependencies"
      - "examples"
