version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "maintenance"
      - "dependencies"
      - "lazyssh"
    groups:
      lazyssh:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "gh-actions"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directories:
      - "/"
      - "/examples"
    schedule:
      interval: "weekly"
    labels:
      - "maintenance"
      - "dependencies"
    groups:
      charm:
        patterns:
          - "charm.land/*"
          - "github.com/charmbracelet/*"
        group-by: dependency-name
      golang-x:
        patterns:
          - "golang.org/x/*"
        group-by: dependency-name
      other:
        patterns:
          - "*"
        exclude-patterns:
          - "charm.land/*"
          - "github.com/charmbracelet/*"
          - "golang.org/x/*"
        group-by: dependency-name
